travis:
  secure:
    BINSTAR_TOKEN: LJL1o+ovbL1egT+U1HZzx/Ck+1UjEyQhvAQSCla85ln2Trld2m3g949ie9ViElGYONA+HVl317BN0S7SvCEHFM2tSKKC5CN6JuvjmU9amF+mAKyWE/mpLBokWxiSMasVpSJNLb9YcSLPQVkk3Je/mhCK2V664v7NoGbvEHKA7PAcXcpmpkochk60Xt/nmATySvmDsMih3ApGBGCrZEdVD1R8m0m58FZpVghGM5OZ92eDj1SJ+EGN22J22Eljye9o4oSdoylHLKMJ+HIJHtxfs1rrX9DutZE3s7xMjO9poDFl3m5jf3GF7orcQJfpwhPnDPfiXZmG8j01EhBpZMsDFmw6KxC88Z2jucEjyFOgpvfFVeoWPYOdAr/VmlydR5dzRcxty3oRnKLFyy3SXHKASwa1D0zTNxteGJ8dGCps7bE75j48DV8EhSPl4Y+78YEYx4Kh5vmuxqrFaGYk1Fe6OC052cBTd6HWsXFR0rZR0giLCqncvtchCmly4XwbECdXVtvknBZ3H1orEmWdDA8G2nTZgPEXN3PP3JNLN+SQ3gSG4B5RCih6v6lu3pV1MEgbgbWVX9twY7c56or+LlVcsTpAhdjOeCWiEgT7+/sxGwLowk3dNGIlLMp4GwJwpxJSdLbYKiSMXP2V6xoPk795qjwUO5Wc80xI1FR68rxLF14=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
